fail_fast: true
default_install_hook_types:
  - pre-commit
  - prepare-commit-msg
  - commit-msg
repos:
  - repo: https://github.com/milin/giticket
    rev: v1.4
    hooks:
    - id: giticket
      stages:
        - prepare-commit-msg
      args:
        - "--regex=#\\d+"
        - "--format={commit_msg}\n\nCloses {ticket}"
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.0.0
    hooks:
        - id: commitlint
          stages:
            - commit-msg
          additional_dependencies:
            - '@joberstein12/commitlint-config'
        - id: commitlint-travis
          stages:
            - manual
          additional_dependencies:
            - '@joberstein12/commitlint-config'
  - repo: https://github.com/joberstein/precommit-semantic-release
    rev: v1.0.1
    hooks:
        - id: semantic-release
          additional_dependencies:
            - "@qiwi/semantic-release-gh-pages-plugin"
          stages:
            - manual