dist: jammy
language: node_js
node_js: lts/*
cache:
  directories:
    - $HOME/.cache/yarn
    - $HOME/.cache/pre-commit
if: branch != tag

env:
  global:
    # GITHUB_TOKEN
    - secure: cyZ4eUFxeOuNEwVoExBsjh/keFmUV68aVOPOKIAyhndw3ZPg7Udl5N59uILWf5saiAuvdcmQKOvKy7hd2bVom5wu84LtVeS6RnLeMr+NzgdqpdmVzlm1ZnEOhs4vRbLb/D7q/nH18zP1XTCQ64QNzSiLvGqKuR9kDdGS1jRUrQjGntA8N9jcg2ObEQZW23ePobujr6FqmOhli9tYLXI7oW68oJ2YkmCLUtfqiKGfFsFFi7Z1h+TmilVrpKTKN+xjhZzfxfF1oItD8W26P2+NH9pFx22qXTVTbNPHuJwR2yIWHqRhLfaRTr4j7+1fQPZqvZIIuV4TIkzHyQD5LnY0FGbG6jZ9ShXoBjZqMBd1ZvZSfOlnT7ZEvblVBAo4QhQGdgBqJV6fO/qUVEQ4x5LikfdtYeVTlZgwR8iWfBcstINVqCKlM2q29MBLWqwUNNNa5J1wT0ZoQtVn8lAfOqAKgECEThCX+m/8UuKaSSUoftFD4232JNc/8Np1k84tx+8oCoC+LE1bh6eHM2T8Bvlof9MbuXX5AgWM+JxHYpIwl46heernkpHadclkjUEYt9l8Ld+5r+NVP4yC0CiSiqIpHf+n6HrIVcbYuubWUVtkptsFKbjqrFiW2qEKNF/8qGAW4saOkVMM4rW4jK5OpFnJeDcrT19gjLsw4q+66IPH94k=

before_install:
  - pip install pre-commit
  - pre-commit install
  - yarn cache clean

script:
  - yarn build
  - yarn test --ci
  - yarn validate:commits

deploy:
  - provider: script
    edge: true
    script: yarn release
    on:
      branch: master