#!/bin/bash

# This script can be used to delete an existing deploy tag locally, as well as tag a
# local commit to be deployed.

DEPLOY_COMMAND=$1

if [[ -z $DEPLOY_COMMAND || ! $DEPLOY_COMMAND =~ ^(app|sendEmail|all)$ ]]; then
	echo "Usage: ./tag-for-deploy (app|sendEmail|all)"
	exit 1;
fi

git tag -d deploy
git tag -a deploy -m "$DEPLOY_COMMAND"

echo "Successfuly tagged latest commit for 'deploy:$DEPLOY_COMMAND'."
