#!/usr/bin/env bash
":" //#; exec /usr/bin/env node --input-type=module - $(basename $0) $@ < $0

import execAsync from './utils/execAsync.mjs';

const [node, filename, hook, messagePath] = process.argv;

console.log(`Running '${hook}' hook...`);

try {
    await execAsync(`npx commitlint --edit "\${messagePath}"`);
} catch (e) {
    const errorMessage = e.stdout || e;
    console.log(errorMessage);
    process.exit(1);
}