name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  ci_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      # Required to authenticate with gh-pages
      - name: Set Git Remote Url
        run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: Setup tmate session - first
        uses: mxschmitt/action-tmate@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      
      - name: Install Commitlint Config
        run: yarn add -D @joberstein12/commitlint-config
      
      - name: Validate Commits
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: '.commitlintrc.json'
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Validate Typescript
        run: yarn tsc

      - name: Execute Tests
        run: yarn test --ci

      - name: Build Application
        run: yarn build

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Deploy Application
        uses: cycjimmy/semantic-release-action@v3
        with:
          branches: |
            [ 
              '${{ github.ref_name	}}'
            ]
          dry_run: ${{ github.ref_name != 'master' }}
          extra_plugins: |
            @qiwi/semantic-release-gh-pages-plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}