name: Continuous Deployment

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  integration:
    uses: ./.github/workflows/integration.yml
    secrets: inherit

  deployment:
    needs: integration
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy Application
        run: yarn release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}