name: Deployment

on:
  workflow_run:
    workflows:
      - Integration
    types:
      - completed
    # branches: 
    #   - master

jobs:
  on_success:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy Application
        uses: cycjimmy/semantic-release-action@v3
        with:
          branches: |
            [ 
              '#133'
            ]
          dry_run: true
          extra_plugins: |
            @qiwi/semantic-release-gh-pages-plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  on_failure:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Skipping deploy; the triggering workflow failed.'
      