name: Continuous Integration

on:
  - push
  - pull_request
  - workflow_call
  - workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Commitlint Config
        run: yarn global add @joberstein12/commitlint-config
      
      - name: Validate Commits
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: './commitlintrc.json'
        env:
          NODE_PATH: /home/runner/.cache/yarn/v6


      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Initialize Pre-Commit
        run: |
          pip install pre-commit
          pre-commit install

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Validate Typescript
        run: yarn tsc

      - name: Execute Tests
        run: yarn test --ci

      - name: Build Application
        run: yarn build