name: Commit Validation

on:
  push:
    branches:
      - '**'
  pull_request:

env:
  IS_PR: ${{ contains(github.event_name, 'pull_request') }}

jobs:
  validate_commits:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      
      - name: Install Commitlint Config
        run: yarn global add @joberstein12/commitlint-config
      
      - name: Validate Commit Range
        if: fromJSON(env.IS_PR)
        env:
          FROM_BRANCH: ${{ github.base_ref }}
          TO_BRANCH: ${{ github.head_ref }}
        run: |
          FROM_COMMIT=$(git rev-list $FROM_BRANCH..$TO_BRANCH | tail -1)
          npx commitlint -V -f $FROM_COMMIT

      - name: Setup tmate session
        if: ${{ failure() && fromJSON(env.IS_PR) }}
        uses: mxschmitt/action-tmate@v3
        
      - name: Validate Latest Commitlint
        if: ${{ !fromJSON(env.IS_PR) }}
        run: npx commitlint -V -f $GITHUB_SHA^